### ISSUE TITLE
Update gallery to reflect column settings

### ISSUE THREAD

**Issue by cameronjonesweb** [MatterSolutions/matter-kit#3]
Currently the gallery columns is 3 columns on mobile and 5 columns on desktop, regardless of the gallery column settings. This should be changed to reflect the settings even if we have to filter `media_view_settings`

**Comment by KawaiiHannah** [comment]
Have updated this now (pulled partly from your solution for another project). 

The cols have been moved to their own sass partial within the gallery component, so if we have to update it on a per-project basis, we can optimise viewport column sizes.
