### ISSUE TITLE
Setup doesn't write db prefix to config.yaml

### ISSUE THREAD

**Issue by cameronjonesweb** [MatterSolutions/matter-kit#8]
Chassis now requires this

**Comment by KawaiiHannah** [comment]
All good! This was patched in the generator earlier, but the generator doesn't automatically update itself, nor notify anyone of updates. 

**Updating the generator:**
`npm update generator-matter-kit -g`

Alternatively, you can update by running `yo` and choosing the 'Update your generators' option.
